apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
  namespace: tis-app
  labels:
    app: nexus-registry
    managed-by: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "192.168.150.138:8082": {
          "username": "admin",
          "password": "adminnexus",
          "auth": "YWRtaW46YWRtaW5uZXh1cw=="
        }
      }
    }
