apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: tis-app
  labels:
    app: backend
    managed-by: argocd
type: Opaque
stringData:
  connection-string: "Server=sqlserver-service,1433;Database=TisDB;User Id=sa;Password=P@ssw0rd123!;TrustServerCertificate=True"