apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
  namespace: tis-app
  labels:
    app: nexus-registry
    managed-by: argocd
type: kubernetes.io/dockercfg
stringData:
  .dockercfg: |
    {
      "auths": {
        "192.168.56.10:8082": {
          "username": "admin",
          "password": "admin",
          "auth": "YWRtaW46YWRtaW4="
        }
      }
    }